# Generated by Django 3.1.7 on 2021-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0010_auto_20210428_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='addressline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
